# Generated by Django 4.1.13 on 2025-04-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_time', models.CharField(max_length=100)),
                ('table_no', models.CharField(max_length=20)),
                ('special_request', models.TextField(blank=True)),
            ],
        ),
    ]
