# Generated by Django 4.1.13 on 2025-04-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='table_no',
            new_name='table',
        ),
    ]
