# Generated by Django 4.1.13 on 2025-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_date_time_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_time', models.DateTimeField()),
                ('table_no', models.IntegerField()),
                ('special_request', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
