# Generated by Django 4.1.13 on 2025-04-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tablereservation_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableReservation',
        ),
    ]
