# Generated by Django 4.1.13 on 2025-04-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
