# Generated by Django 4.1.13 on 2025-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_time', models.DateTimeField()),
                ('table_no', models.IntegerField()),
                ('special_request', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
