# Generated by Django 4.1.13 on 2025-04-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_booking_delete_tablereservation'),
    ]

    operations = [
    ]
