# Generated by Django 4.1.13 on 2026-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='special_request',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
