# Generated by Django 4.1.13 on 2026-08-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='login',
            table='user_login',
        ),
    ]
