# Generated by Django 4.1.13 on 2026-08-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_login_created_at_alter_login_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='register',
        ),
    ]
