# Generated by Django 4.1.13 on 2026-08-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_student_alter_login_table_alter_userprofile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
